apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-data
  namespace: trilium
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-synology
  resources:
    requests:
      storage: 2Gi
