---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: joplin-backup-secret
  namespace: joplin-backup
spec:
  encryptedData:
    GIT_TOKEN: AgBKa7ijiGOfi27GCG9ZZJ7wJ2qGX5mgr04GtHTUQDmoVL0zxjnAHn+aoyS1imJyfzBGL9ffy5fDXcdYeW5gEKyAs7DaS1pFj+rOvLG7E5ROGza4qufrYxVn3VuLOfQvwg2CNKpMHp5G/B52KvRToXOU1vupGxgGFhJDKOzEP08kkfiv67WsiXZjJaVSw6FXrBdaWAV7Gm22Usy5H2dNRwixjvm6vhyRh6VeJqXRGuRPPZ44f9EJEnRyUuyxExGOf9v3rLawZNQIHtlDoXFIOpNCgtHskaew5nDCuN/xa/8v412/dGcsL5C1TGnqSPetPz9ImFzTBQAwOXyvzj+82Y6X/J2XSqA2xBqNoKmJbDokIBiP2ovAmu2W5FjSlP2ugqPde7hqf+lbIRmFa1dvpra15UkjqXymVLNPjjERpiT8FX/3qpXFJFDK/8IQvYqo8hZND9tpVMFY75XH1/EfrcQ7Dl97x8b8l8XhYVhmEGvwPVThR8RJd5iIdN15kdC2RWWTOur+1qtetOgY3YD+HvdoqrY2i0T662YwvS3Hx+9Oho8/qEoShAlDkZLpbdeLNPc2BNRrjmZMCjsRJJwkATK9zUsaosGVF2Rcptsz1OM4Y3xSlAEC2UAkC0qVzr829qORAMJQXzJqLh37SeE3dh0C4jZEyhYNru1ViIVcMDrfB+0pf9vOLSSEXAkoMfazbsRV0AQt3bV7CaA4XnAGTY3YmEv+0hqlA1nVcJ9yc7yMNpeGcEWcBECGLCdkd3LcRMJ+zYQFxXwPj2r5d5XVTEGAasZVgNT32Wlso+1Fo8q72ZNOc9NpxSIvvE687/g=
    GIT_USERNAME: AgB5cEk9KB2Z+fKbdOoKYf3+AV2iSh9kPprE2WsgNoC3hYC97I++ml1i+647YF6qkuO5scNLZ4i9+WcRJ8cUDPOxA0J+5Utx3NxwugJGEJDvWM88038YGH7Ch4sS9QdaWDatY9XVrQ1Kw9eEBAtCKtW0cTu3hn3NAabedJAb9ZZ8u5a3+Wwyk33HBzaNstFgUqMnYx11/5yGWcQ09ba7H/KJYNTZnRqVkzg1WewurDfCSNwrbZzFxHWMtp+Ram4jN1hO8kp0W6y0SzL9R+9W9QlDDPDeG1mO5ExuzRUhm08u6gdbvPHwlKNz7lnRTx7CJjmDNSDd8BbnzmwEuuJXK8yYv1aqzo+CC0vClCeLFinzHyMF0jqbUOSFK2HfhaB9BLubH3topeiGub4z4z3Kq0ewgmrgTGNXtJwWo/H6DJPoSxfhF6xLzUrVxZaYm285arZCpzvqB+qz6cXyjfSYPHdqD5maoQAUs4Yxb/79/NctiPb2JJ7CxqUGEkOcJNt49dRJWZruwmclfgmc05jbLeZj775T6Ve2CJVZS1LMNXwfy/5Kt7aSwtIDP1JyzorKrLxwVz2S99d9SaUNUOBxni+P6EEP8lVE+DrvjveO/9pTFpYjP6WXTpS6WL8+tKLw2ia/YZWXCdnYUITuV/B8MNQgzTcK1uzqQ23kcd34sqLNh80p71FBOd3XDHU+Yd26l5Qr2y4ULZXprVEQgA==
  template:
    metadata:
      creationTimestamp: null
      name: joplin-backup-secret
      namespace: joplin-backup
    type: Opaque
