apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-runner-work
  namespace: github-runner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-synology
  resources:
    requests:
      storage: 3Gi
