apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default
  
  # Source: Where the manifests are stored
  source:
    repoURL: https://github.com/Ling-Ling23/k3s_homelab_with_nas.git
    targetRevision: main
    path: k3s/argocd/demo-app
  
  # Destination: Where to deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true      # Remove resources when deleted from Git
      selfHeal: true   # Auto-sync when cluster state differs
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true  # Auto-create namespace
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
