apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: "*"
      helm:
        releaseName: loki
        valueFiles:
          - $values/k3s/argocd/projects/infra/logging/helm_values/loki-values.yaml
    - repoURL: https://grafana.github.io/helm-charts
      chart: promtail
      targetRevision: "*"
      helm:
        releaseName: promtail
        valueFiles:
          - $values/k3s/argocd/projects/infra/logging/helm_values/promtail-values.yaml
    - repoURL: https://github.com/Ling-Ling23/k3s_homelab_with_nas.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/Ling-Ling23/k3s_homelab_with_nas.git
      targetRevision: main
      path: k3s/argocd/projects/infra/logging
      directory:
        recurse: false
        exclude: "helm_values/**"

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
