---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBlCnSx8FTd5qsYgGIgPxf212DZkAIIy+p2fmY5NOj/pTPAgK8fo4mEkundHC0a862BW8FLnGuewXyhRx8Pxy1BD6XRzGBo+oCpG7mNOV5n39QD54prMPCvAc2H9kaMiORNnCLSVpJDJ6x0n939ql6VsXk7U+SZHGgE/ZagzLXzl9M1xcrzvdbQSq31O5F5qitfbrzs/rJ/i/su4raaxDC+dnVTs6zr1wmbvKYn0ZTo5LYBYUkiYeZxqL5UyeFTLzd2/t/YpaGxlZJ+a/ZbyD+JUvJZv6l6lOLHu9/moi/YAAnRR29D90RrmiQmv/VTm3BTgD8LiXcJySlvZZHSX+RkIJ6eg5Oe3yTutNbE5U40SLOPll9DcHzEDNFEhwhSZnKkFviSHdrB7To5kjINhn8FxmvS3Cznagr5d8SnYxPEWAqATaCUn1dfvfXMVG7oLyCeQfolyAkurnZppAwmgHTd+lQggsclhmGHQ6//VnrzqKXJVEXkvCBSBhU+2WN+mjYErQlzeVTbBPkPZnlLHtQPtcXcPH9z45UaddCQ6ER+Tnp29HdorO+nFZPiT4aNUawEh4CYLWl/PBew68Yr2S/ivXFRukzAznoNf3srysutKf8T+Ybn/V2vD3Gwf3w8l/CiutX5yOobutvMWYuvkKtfL/bMw0ZjEVmf1xO8Mgpo3dby2ido76fcMSvtSD3emZ2CbBnwRlENPk+hYbD9rpj82HjUDTsu06pHTR2hQpk7DyqzdG/2t44/O17YnJcQr+z/wkX99j6BbdSJd0/GsoxHkSZmNNJK89g/4wOXDtmjoA==
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
      annotations:
        argocd.argoproj.io/sync-wave: "0"